image: registry.secoder.net/tool/deployer

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: 
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
  only:
    - master
    - dev

.test:
  image: mongo:latest
  stage: test

  before_script:
    - pwd
    - apt-get update
    - apt-get install wget
    - apt-get install xz-utils
    - apt-get install curl
    - mkdir /testse
    - wget https://nodejs.org/dist/v16.20.1/node-v16.20.1-linux-x64.tar.xz -O /testse/node-v16.20.1-linux-x64.tar.xz
    - tar -xJvf /testse/node-v16.20.1-linux-x64.tar.xz -C /testse
    - ls -la /testse
    - ls -la /testse/node-v16.20.1-linux-x64
    - ln -s /testse/node-v16.20.1-linux-x64/bin/node /usr/bin/node
    - ln -s /testse/node-v16.20.1-linux-x64/bin/npm /usr/bin/npm
    - ln -s /testse/node-v16.20.1-linux-x64/bin/npx /usr/bin/npx
    - node -v
    - npm -v
    - /testse/node-v16.20.1-linux-x64/bin/npm config set registry https://registry.npmmirror.com
    - /testse/node-v16.20.1-linux-x64/bin/npm install -g yarn
    - /testse/node-v16.20.1-linux-x64/lib/node_modules/yarn/bin/yarn config set registry https://registry.npmmirror.com
    - /testse/node-v16.20.1-linux-x64/lib/node_modules/yarn/bin/yarn

unit-test:
  extends: .test
  script:
    - nohup mongod &
    - /testse/node-v16.20.1-linux-x64/lib/node_modules/yarn/bin/yarn test --passWithNoTests --runInBand
    - ls -la .
    - kill -9 `ps aux | grep mongod | awk '{print $2}' | head -n 1`
  after_script:
    - SUFFIX=$RANDOM
    - curl "http://api.secoder.net/static/sonar-scanner-cli-5.tar.gz" -s -o "/tmp/sonar-$SUFFIX.tar.gz"
    - tar -xf "/tmp/sonar-$SUFFIX.tar.gz" -C /opt
    - /opt/sonar-scanner/bin/sonar-scanner -Dsonar.token=sqp_46e7ae3301a9b2da5bc835068cb78a466a6a0065

style-test:
  extends: .test
  script:
    - /testse/node-v16.20.1-linux-x64/lib/node_modules/yarn/bin/yarn lint

deploy:
  stage: deploy
  script:
    - deployer dyno replace $CI_PROJECT_NAME "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  only:
    - master
    - dev